# Generated by Django 5.0.1 on 2024-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
